import { Link } from "wouter";
import { Loader2, Search as SearchIcon, UserRound, BriefcaseBusiness } from "lucide-react";
import { trpc } from "@/lib/trpc";
import AppChrome from "@/components/AppChrome";

export default function SearchPage() {
  const query = new URLSearchParams(window.location.search).get("q") || "";
  const { data, isLoading, isError } = trpc.search.all.useQuery({ q: query }, { enabled: query.trim().length > 0 });
  return <AppChrome title="نتائج البحث"><div className="container py-8"><div className="mx-auto max-w-4xl rounded-[1.75rem] border border-neutral-200 bg-white p-6"><div className="flex items-center gap-3 border-b border-neutral-100 pb-5"><SearchIcon className="h-5 w-5 text-[#c38a10]" /><div><h2 className="font-display text-xl font-bold">البحث في KING DESIGNER</h2><p className="mt-1 text-sm text-neutral-500">نتائج حقيقية من الحسابات والأعمال والوسوم المحفوظة في قاعدة البيانات.</p></div></div>{!query.trim() ? <div className="py-20 text-center text-sm text-neutral-500">اكتب كلمة بحث أو استخدم @ للبحث عن حساب و# للبحث عن وسم.</div> : isLoading ? <div className="grid place-items-center py-20"><Loader2 className="animate-spin text-[#c38a10]" /></div> : isError ? <div className="py-20 text-center text-sm text-red-600">تعذر تنفيذ البحث.</div> : <div className="mt-6 space-y-8"><section><div className="mb-3 flex items-center gap-2 font-bold"><UserRound className="h-4 w-4 text-[#c38a10]" />الحسابات</div>{data?.users.length ? <div className="grid gap-3 sm:grid-cols-2">{data.users.map(person => <Link key={person.id} href={`/profile/${person.id}`} className="flex items-center gap-3 rounded-2xl border border-neutral-100 p-4 transition hover:border-[#ead48d]"><div className="grid h-10 w-10 place-items-center overflow-hidden rounded-xl bg-neutral-950 text-xs font-bold text-[#f6c94c]">{person.avatarUrl ? <img src={person.avatarUrl} alt={person.name || "المستخدم"} className="h-full w-full object-cover" /> : (person.name || "KD").slice(0, 2)}</div><div><p className="font-bold">{person.name || "مستخدم"}</p><p className="mt-1 text-xs text-neutral-400">{person.specialty || "مصمم مستقل"}</p><p className="mt-1 text-[11px] font-bold text-[#a36e00]">{person.publicId ? `ID: ${person.publicId}` : ""}{person.handle ? ` · @${person.handle}` : ""}</p></div></Link>)}</div> : <p className="text-sm text-neutral-400">لا توجد حسابات مطابقة.</p>}</section><section><div className="mb-3 flex items-center gap-2 font-bold"><BriefcaseBusiness className="h-4 w-4 text-[#c38a10]" />الأعمال والوسوم</div>{data?.posts.length ? <div className="space-y-3">{data.posts.map(({ post, author }) => <Link key={post.id} href={`/profile/${author.id}`} className="block rounded-2xl border border-neutral-100 p-4 transition hover:border-[#ead48d]"><p className="font-bold">{post.title}</p><p className="mt-1 line-clamp-2 text-sm leading-6 text-neutral-500">{post.description || "عمل إبداعي منشور"}</p><p className="mt-2 text-xs text-[#a36e00]">بواسطة {author.name || "مستخدم"}{post.hashtags ? ` · ${post.hashtags}` : ""}</p></Link>)}</div> : <p className="text-sm text-neutral-400">لا توجد أعمال أو وسوم مطابقة.</p>}</section></div>}</div></div></AppChrome>;
}
