import { z } from "zod";
import { and, desc, eq, inArray, like, ne, or } from "drizzle-orm";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { adminProcedure, protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { getDb, getProfile, listFeed, createNotification, isBlocked, getConversation, sortInboxItems, posts, users, postLikes, comments, follows, blocks, notifications, conversations, conversationMembers, messages, splashSlides, postMedia, postShares, commentLikes, reports, creditLedger, payments, subscriptions, aiProviders, aiModels, pricingPlans, rewards, adminAuditLogs } from "./db";
import { storagePut } from "./storage";
import { ENV } from "./_core/env";
import { canAssignPublicId, decodeUploadData, getLevelForPublishedPosts } from "./validation";

const storedImageUrl = z.string().min(1).max(1000).refine(value => value.startsWith("/manus-storage/") || /^https?:\/\//.test(value), "رابط الصورة غير صالح");
const profileInput = z.object({ name: z.string().min(2).max(120).optional(), handle: z.string().regex(/^[A-Za-z0-9_\u0600-\u06FF]{3,80}$/).optional(), bio: z.string().max(600).optional(), country: z.string().max(120).optional(), specialty: z.string().max(160).optional(), avatarUrl: storedImageUrl.optional(), coverUrl: storedImageUrl.optional() });

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(opts => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }),
  }),
  profile: router({
    get: publicProcedure.input(z.object({ userId: z.number().int().positive() })).query(async ({ input, ctx }) => { if (ctx.user && ctx.user.id !== input.userId && await isBlocked(ctx.user.id, input.userId)) return null; return getProfile(input.userId); }),
    posts: publicProcedure.input(z.object({ userId: z.number().int().positive() })).query(async ({ input, ctx }) => { if (ctx.user && ctx.user.id !== input.userId && await isBlocked(ctx.user.id, input.userId)) return []; const db = await getDb(); if (!db) return []; const rows = await db.select({ post: posts, author: users }).from(posts).innerJoin(users, eq(posts.authorId, users.id)).where(eq(posts.authorId, input.userId)).orderBy(desc(posts.createdAt)); return Promise.all(rows.map(async ({ post, author }) => { const [likes, commentCount, shares] = await Promise.all([db.select().from(postLikes).where(eq(postLikes.postId, post.id)), db.select().from(comments).where(eq(comments.postId, post.id)), db.select().from(postShares).where(eq(postShares.postId, post.id))]); return { ...post, author, media: await db.select().from(postMedia).where(eq(postMedia.postId, post.id)), likesCount: likes.length, commentsCount: commentCount.length, sharesCount: shares.length, liked: Boolean(ctx.user && likes.some(like => like.userId === ctx.user?.id)) }; })); }),
    update: protectedProcedure.input(profileInput).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const { country: _country, ...editable } = input; await db.update(users).set(editable).where(eq(users.id, ctx.user.id)); return getProfile(ctx.user.id); }),
    detectCountry: protectedProcedure.query(async ({ ctx }) => { const db = await getDb(); if (!db) return getProfile(ctx.user.id); const current = await getProfile(ctx.user.id); if (current?.country) return current; const headers = ctx.req.headers as Record<string, string | string[] | undefined>; const detected = String(headers["cf-ipcountry"] || headers["x-vercel-ip-country"] || headers["x-country"] || "").trim().toUpperCase(); if (detected && detected !== "UN" && detected !== "UNKNOWN") { await db.update(users).set({ country: detected, countryLocked: 1 }).where(eq(users.id, ctx.user.id)); } return getProfile(ctx.user.id); }),
  }),
  feed: router({ list: publicProcedure.query(({ ctx }) => listFeed(ctx.user?.id)) }),
  search: router({ all: publicProcedure.input(z.object({ q: z.string().min(1).max(120) })).query(async ({ input, ctx }) => { const db = await getDb(); if (!db) return { users: [], posts: [] }; const cleanQuery = input.q.replace(/^[@#]/, "").trim(); const term = `%${cleanQuery}%`; const blockedRows = ctx.user ? await db.select().from(blocks).where(or(eq(blocks.blockerId, ctx.user.id), eq(blocks.blockedId, ctx.user.id))) : []; const blockedIds = new Set(blockedRows.flatMap(row => [row.blockerId, row.blockedId]).filter(id => id !== ctx.user?.id)); const foundUsers = await db.select({ id: users.id, publicId: users.publicId, name: users.name, handle: users.handle, specialty: users.specialty, avatarUrl: users.avatarUrl, verified: users.verified, level: users.level }).from(users).where(or(eq(users.publicId, cleanQuery), like(users.name, term), like(users.handle, term), like(users.email, term), like(users.specialty, term))).limit(12); const foundPosts = await db.select({ post: posts, author: users }).from(posts).innerJoin(users, eq(posts.authorId, users.id)).where(or(like(posts.title, term), like(posts.description, term), like(posts.hashtags, term))).orderBy(desc(posts.createdAt)).limit(20); return { users: foundUsers.filter(user => !blockedIds.has(user.id)), posts: foundPosts.filter(row => !blockedIds.has(row.author.id)) }; }), resolveMentions: publicProcedure.input(z.object({ handles: z.array(z.string().min(1).max(120)).max(50) })).query(async ({ input }) => { const db = await getDb(); const resolved: Record<string, number> = {}; if (!db || !input.handles.length) return resolved; await Promise.all(input.handles.map(async handle => { const clean = handle.replace(/^@/, ""); const rows = await db.select({ id: users.id }).from(users).where(eq(users.handle, clean)).limit(1); if (rows[0]) resolved[clean] = rows[0].id; })); return resolved; }) }),
  posts: router({
    create: protectedProcedure.input(z.object({ title: z.string().min(2).max(220), description: z.string().max(5000).optional(), category: z.string().max(100).optional(), hashtags: z.string().max(1000).optional(), visibility: z.enum(["public", "followers", "private"]).default("public"), media: z.array(z.object({ mediaType: z.enum(["image", "video"]), url: z.string(), fileKey: z.string() })).max(12).default([]) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const result = await db.insert(posts).values({ authorId: ctx.user.id, title: input.title, description: input.description, category: input.category, hashtags: input.hashtags, visibility: input.visibility }); const postId = Number(result[0].insertId); if (input.media.length) await db.insert(postMedia).values(input.media.map((media, sortOrder) => ({ ...media, postId, sortOrder })));
      const publishedPosts = await db.select({ id: posts.id }).from(posts).where(and(eq(posts.authorId, ctx.user.id), eq(posts.visibility, "public")));
      const levelNumber = getLevelForPublishedPosts(publishedPosts.length);
      await db.update(users).set({ level: String(levelNumber) }).where(eq(users.id, ctx.user.id));
      return { id: postId, level: levelNumber, publishedPosts: publishedPosts.length }; }),
    update: protectedProcedure.input(z.object({ postId: z.number().int().positive(), title: z.string().min(2).max(220), description: z.string().max(5000).optional(), category: z.string().max(100).optional(), hashtags: z.string().max(1000).optional(), visibility: z.enum(["public", "followers", "private"]) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const post = (await db.select().from(posts).where(eq(posts.id, input.postId)).limit(1))[0]; if (!post || post.authorId !== ctx.user.id) throw new Error("Not allowed"); await db.update(posts).set({ title: input.title, description: input.description, category: input.category, hashtags: input.hashtags, visibility: input.visibility }).where(eq(posts.id, input.postId)); return { success: true }; }),
    delete: protectedProcedure.input(z.object({ postId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const post = (await db.select().from(posts).where(eq(posts.id, input.postId)).limit(1))[0]; if (!post || post.authorId !== ctx.user.id) throw new Error("Not allowed"); const postComments = await db.select({ id: comments.id }).from(comments).where(eq(comments.postId, input.postId)); const commentIds = postComments.map(comment => comment.id); if (commentIds.length) await db.delete(commentLikes).where(inArray(commentLikes.commentId, commentIds)); await db.delete(comments).where(eq(comments.postId, input.postId)); await db.delete(postLikes).where(eq(postLikes.postId, input.postId)); await db.delete(postShares).where(eq(postShares.postId, input.postId)); await db.delete(postMedia).where(eq(postMedia.postId, input.postId)); await db.delete(notifications).where(eq(notifications.postId, input.postId)); await db.delete(posts).where(eq(posts.id, input.postId)); return { success: true }; }),
    toggleLike: protectedProcedure.input(z.object({ postId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const post = (await db.select().from(posts).where(eq(posts.id, input.postId)).limit(1))[0]; if (!post || await isBlocked(ctx.user.id, post.authorId)) throw new Error("Interaction unavailable"); const existing = (await db.select().from(postLikes).where(and(eq(postLikes.postId, input.postId), eq(postLikes.userId, ctx.user.id))).limit(1))[0]; if (existing) { await db.delete(postLikes).where(eq(postLikes.id, existing.id)); return { liked: false }; } await db.insert(postLikes).values({ postId: input.postId, userId: ctx.user.id }); await createNotification(post.authorId, ctx.user.id, "like", post.id); return { liked: true }; }),
    share: protectedProcedure.input(z.object({ postId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const post = (await db.select().from(posts).where(eq(posts.id, input.postId)).limit(1))[0]; if (!post || await isBlocked(ctx.user.id, post.authorId)) throw new Error("Interaction unavailable"); const existing = (await db.select().from(postShares).where(and(eq(postShares.postId, input.postId), eq(postShares.userId, ctx.user.id))).limit(1))[0]; if (!existing) { await db.insert(postShares).values({ postId: input.postId, userId: ctx.user.id }); await createNotification(post.authorId, ctx.user.id, "share", post.id); } return { shared: true }; }),
    interactors: publicProcedure.input(z.object({ postId: z.number().int().positive() })).query(async ({ input, ctx }) => { const db = await getDb(); if (!db) return { likes: [], comments: [] }; const likes = await db.select({ user: users }).from(postLikes).innerJoin(users, eq(postLikes.userId, users.id)).where(eq(postLikes.postId, input.postId)); const commentRows = await db.select({ comment: comments, author: users }).from(comments).innerJoin(users, eq(comments.authorId, users.id)).where(eq(comments.postId, input.postId)).orderBy(desc(comments.createdAt)); if (!ctx.user) return { likes, comments: commentRows }; const visibleLikes = (await Promise.all(likes.map(async row => ({ row, blocked: await isBlocked(ctx.user!.id, row.user.id) })))).filter(item => !item.blocked).map(item => item.row); const visibleComments = (await Promise.all(commentRows.map(async row => ({ row, blocked: await isBlocked(ctx.user!.id, row.author.id) })))).filter(item => !item.blocked).map(item => item.row); return { likes: visibleLikes, comments: visibleComments }; }),
  }),
  comments: router({
    list: publicProcedure.input(z.object({ postId: z.number().int().positive() })).query(async ({ input, ctx }) => { const db = await getDb(); if (!db) return []; const rows = await db.select({ comment: comments, author: users }).from(comments).innerJoin(users, eq(comments.authorId, users.id)).where(eq(comments.postId, input.postId)).orderBy(desc(comments.createdAt)); const visibleRows = ctx.user ? (await Promise.all(rows.map(async row => ({ row, blocked: await isBlocked(ctx.user!.id, row.author.id) })))).filter(item => !item.blocked).map(item => item.row) : rows; return Promise.all(visibleRows.map(async row => { const likes = await db.select().from(commentLikes).where(eq(commentLikes.commentId, row.comment.id)); return { ...row, likesCount: likes.length, liked: Boolean(ctx.user && likes.some(like => like.userId === ctx.user?.id)) }; })); }),
    create: protectedProcedure.input(z.object({ postId: z.number().int().positive(), body: z.string().min(1).max(2000), parentId: z.number().int().positive().optional(), mediaUrl: z.string().optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const post = (await db.select().from(posts).where(eq(posts.id, input.postId)).limit(1))[0]; if (!post || await isBlocked(ctx.user.id, post.authorId)) throw new Error("Interaction unavailable"); const result = await db.insert(comments).values({ postId: input.postId, authorId: ctx.user.id, body: input.body, parentId: input.parentId, mediaUrl: input.mediaUrl }); const commentId = Number(result[0].insertId); await createNotification(post.authorId, ctx.user.id, input.parentId ? "reply" : "comment", post.id, commentId); return { id: commentId }; }),
    toggleLike: protectedProcedure.input(z.object({ commentId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const existing = (await db.select().from(commentLikes).where(and(eq(commentLikes.commentId, input.commentId), eq(commentLikes.userId, ctx.user.id))).limit(1))[0]; if (existing) { await db.delete(commentLikes).where(eq(commentLikes.id, existing.id)); return { liked: false }; } await db.insert(commentLikes).values({ commentId: input.commentId, userId: ctx.user.id }); return { liked: true }; }),
    delete: protectedProcedure.input(z.object({ commentId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const comment = (await db.select({ comment: comments, post: posts }).from(comments).innerJoin(posts, eq(comments.postId, posts.id)).where(eq(comments.id, input.commentId)).limit(1))[0]; if (!comment || (comment.comment.authorId !== ctx.user.id && comment.post.authorId !== ctx.user.id)) throw new Error("Not allowed"); await db.delete(comments).where(eq(comments.id, input.commentId)); return { success: true }; }),
  }),
  social: router({
    relationship: protectedProcedure.input(z.object({ userId: z.number().int().positive() })).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) return { following: false, incoming: null, blocked: false }; const [outgoing, incoming, blocked] = await Promise.all([db.select().from(follows).where(and(eq(follows.followerId, ctx.user.id), eq(follows.followingId, input.userId))).limit(1), db.select().from(follows).where(and(eq(follows.followerId, input.userId), eq(follows.followingId, ctx.user.id))).limit(1), db.select().from(blocks).where(and(eq(blocks.blockerId, ctx.user.id), eq(blocks.blockedId, input.userId))).limit(1)]); return { following: outgoing[0]?.status || false, incoming: incoming[0]?.status || null, blocked: Boolean(blocked[0]) }; }),
    requestFollow: protectedProcedure.input(z.object({ userId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { if (ctx.user.id === input.userId) throw new Error("Cannot follow yourself"); const db = await getDb(); if (!db || await isBlocked(ctx.user.id, input.userId)) throw new Error("Unavailable"); const existing = (await db.select().from(follows).where(and(eq(follows.followerId, ctx.user.id), eq(follows.followingId, input.userId))).limit(1))[0]; if (existing) return { status: existing.status }; await db.insert(follows).values({ followerId: ctx.user.id, followingId: input.userId, status: "pending" }); await createNotification(input.userId, ctx.user.id, "follow"); return { status: "pending" as const }; }),
    respondFollow: protectedProcedure.input(z.object({ followerId: z.number().int().positive(), accept: z.boolean() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const existing = (await db.select().from(follows).where(and(eq(follows.followerId, input.followerId), eq(follows.followingId, ctx.user.id))).limit(1))[0]; if (!existing) throw new Error("Request not found"); if (input.accept) await db.update(follows).set({ status: "accepted" }).where(eq(follows.id, existing.id)); else await db.delete(follows).where(eq(follows.id, existing.id)); return { accepted: input.accept }; }),
    toggleFollow: protectedProcedure.input(z.object({ userId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { if (ctx.user.id === input.userId) throw new Error("Cannot follow yourself"); const db = await getDb(); if (!db || await isBlocked(ctx.user.id, input.userId)) throw new Error("Unavailable"); const existing = (await db.select().from(follows).where(and(eq(follows.followerId, ctx.user.id), eq(follows.followingId, input.userId))).limit(1))[0]; if (existing) { await db.delete(follows).where(eq(follows.id, existing.id)); return { following: false }; } await db.insert(follows).values({ followerId: ctx.user.id, followingId: input.userId, status: "accepted" }); await createNotification(input.userId, ctx.user.id, "follow"); return { following: true }; }),
    toggleBlock: protectedProcedure.input(z.object({ userId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const existing = (await db.select().from(blocks).where(and(eq(blocks.blockerId, ctx.user.id), eq(blocks.blockedId, input.userId))).limit(1))[0]; if (existing) { await db.delete(blocks).where(eq(blocks.id, existing.id)); return { blocked: false }; } await db.insert(blocks).values({ blockerId: ctx.user.id, blockedId: input.userId }); return { blocked: true }; }),
  }),
  notifications: router({ list: protectedProcedure.query(async ({ ctx }) => { const db = await getDb(); if (!db) return []; return db.select({ notification: notifications, actor: users }).from(notifications).innerJoin(users, eq(notifications.actorId, users.id)).where(eq(notifications.recipientId, ctx.user.id)).orderBy(desc(notifications.createdAt)).limit(50); }), markRead: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(notifications).set({ isRead: 1 }).where(and(eq(notifications.id, input.id), eq(notifications.recipientId, ctx.user.id))); return { success: true }; }) }),
  reports: router({ create: protectedProcedure.input(z.object({ targetType: z.enum(["user", "post", "comment", "message"]), targetId: z.number().int().positive(), reason: z.string().min(3).max(2000) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.insert(reports).values({ reporterId: ctx.user.id, targetType: input.targetType, targetId: input.targetId, reason: input.reason }); return { success: true }; }) }),
  adminControl: router({
    users: adminProcedure.query(async () => { const db = await getDb(); if (!db) return []; return db.select({ id: users.id, publicId: users.publicId, name: users.name, email: users.email, handle: users.handle, role: users.role, verified: users.verified, country: users.country, createdAt: users.createdAt }).from(users).orderBy(desc(users.createdAt)).limit(200); }),
    profiles: adminProcedure.query(async () => { const db = await getDb(); if (!db) return []; return db.select({ id: users.id, publicId: users.publicId, name: users.name, bio: users.bio, country: users.country, specialty: users.specialty, level: users.level, avatarUrl: users.avatarUrl, coverUrl: users.coverUrl, verified: users.verified }).from(users).orderBy(desc(users.updatedAt)).limit(200); }),
    posts: adminProcedure.query(async () => { const db = await getDb(); if (!db) return []; return db.select({ post: posts, author: users }).from(posts).innerJoin(users, eq(posts.authorId, users.id)).orderBy(desc(posts.createdAt)).limit(200); }),
    comments: adminProcedure.query(async () => { const db = await getDb(); if (!db) return []; return db.select({ comment: comments, author: users }).from(comments).innerJoin(users, eq(comments.authorId, users.id)).orderBy(desc(comments.createdAt)).limit(200); }),
    blocks: adminProcedure.query(async () => { const db = await getDb(); if (!db) return []; return db.select().from(blocks).orderBy(desc(blocks.createdAt)).limit(200); }),
    reports: adminProcedure.query(async () => { const db = await getDb(); if (!db) return []; return db.select().from(reports).orderBy(desc(reports.createdAt)).limit(200); }),
    messages: adminProcedure.query(async () => { const db = await getDb(); if (!db) return []; return db.select().from(messages).orderBy(desc(messages.createdAt)).limit(200); }),
    credits: adminProcedure.query(async () => { const db = await getDb(); if (!db) return []; return db.select().from(creditLedger).orderBy(desc(creditLedger.createdAt)).limit(200); }),
    payments: adminProcedure.query(async () => { const db = await getDb(); if (!db) return []; return db.select().from(payments).orderBy(desc(payments.createdAt)).limit(200); }),
    subscriptions: adminProcedure.query(async () => { const db = await getDb(); if (!db) return []; return db.select().from(subscriptions).orderBy(desc(subscriptions.startsAt)).limit(200); }),
    aiProviders: adminProcedure.query(async () => { const db = await getDb(); if (!db) return []; return db.select().from(aiProviders).orderBy(desc(aiProviders.createdAt)); }),
    aiModels: adminProcedure.query(async () => { const db = await getDb(); if (!db) return []; return db.select().from(aiModels).orderBy(desc(aiModels.id)); }),
    pricing: adminProcedure.query(async () => { const db = await getDb(); if (!db) return []; return db.select().from(pricingPlans).orderBy(desc(pricingPlans.id)); }),
    rewards: adminProcedure.query(async () => { const db = await getDb(); if (!db) return []; return db.select().from(rewards).orderBy(desc(rewards.createdAt)).limit(200); }),
    notifications: adminProcedure.query(async () => { const db = await getDb(); if (!db) return []; return db.select().from(notifications).orderBy(desc(notifications.createdAt)).limit(200); }),
    deletePost: adminProcedure.input(z.object({ postId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const postComments = await db.select({ id: comments.id }).from(comments).where(eq(comments.postId, input.postId)); const commentIds = postComments.map(item => item.id); if (commentIds.length) await db.delete(commentLikes).where(inArray(commentLikes.commentId, commentIds)); await db.delete(comments).where(eq(comments.postId, input.postId)); await db.delete(postLikes).where(eq(postLikes.postId, input.postId)); await db.delete(postShares).where(eq(postShares.postId, input.postId)); await db.delete(postMedia).where(eq(postMedia.postId, input.postId)); await db.delete(notifications).where(eq(notifications.postId, input.postId)); await db.delete(posts).where(eq(posts.id, input.postId)); await db.insert(adminAuditLogs).values({ adminId: ctx.user.id, action: "admin_delete_post", entity: "post", entityId: String(input.postId) }); return { success: true }; }),
    deleteMessage: adminProcedure.input(z.object({ messageId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.delete(messages).where(eq(messages.id, input.messageId)); await db.insert(adminAuditLogs).values({ adminId: ctx.user.id, action: "admin_delete_message", entity: "message", entityId: String(input.messageId) }); return { success: true }; }),
    setSubscriptionPlan: adminProcedure.input(z.object({ userId: z.number().int().positive(), plan: z.enum(["free", "pro", "vip"]), status: z.enum(["active", "canceled"]).default("active") })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const current = (await db.select({ id: subscriptions.id }).from(subscriptions).where(eq(subscriptions.userId, input.userId)).limit(1))[0]; if (current) await db.update(subscriptions).set({ plan: input.plan, status: input.status }).where(eq(subscriptions.id, current.id)); else await db.insert(subscriptions).values({ userId: input.userId, plan: input.plan, status: input.status }); await db.insert(adminAuditLogs).values({ adminId: ctx.user.id, action: "set_subscription", entity: "user", entityId: String(input.userId), details: `${input.plan}:${input.status}` }); return { success: true }; }),
    updatePricingPlan: adminProcedure.input(z.object({ planId: z.number().int().positive(), name: z.string().min(2).max(120), credits: z.number().int().min(0), amountCents: z.number().int().min(0), isActive: z.boolean() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(pricingPlans).set({ name: input.name, credits: input.credits, amountCents: input.amountCents, isActive: input.isActive ? 1 : 0 }).where(eq(pricingPlans.id, input.planId)); await db.insert(adminAuditLogs).values({ adminId: ctx.user.id, action: "update_pricing", entity: "pricing_plan", entityId: String(input.planId) }); return { success: true }; }),
    grantReward: adminProcedure.input(z.object({ userId: z.number().int().positive(), amount: z.number().int().positive().max(100000), referenceId: z.string().min(4).max(160) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const marker = `reward:${input.referenceId}`; const alreadyGranted = (await db.select({ id: adminAuditLogs.id }).from(adminAuditLogs).where(and(eq(adminAuditLogs.action, "grant_reward"), eq(adminAuditLogs.details, marker))).limit(1))[0]; if (alreadyGranted) throw new Error("تم تنفيذ هذه المكافأة مسبقًا"); await db.insert(rewards).values({ userId: input.userId, type: "manual", amount: input.amount }); await db.insert(creditLedger).values({ userId: input.userId, amount: input.amount, kind: "reward", referenceId: input.referenceId, createdById: ctx.user.id }); await db.insert(adminAuditLogs).values({ adminId: ctx.user.id, action: "grant_reward", entity: "user", entityId: String(input.userId), details: marker }); return { success: true }; }),
    deleteComment: adminProcedure.input(z.object({ commentId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.delete(commentLikes).where(eq(commentLikes.commentId, input.commentId)); await db.delete(comments).where(eq(comments.id, input.commentId)); await db.insert(adminAuditLogs).values({ adminId: ctx.user.id, action: "delete_comment", entity: "comment", entityId: String(input.commentId) }); return { success: true }; }),
    setBan: adminProcedure.input(z.object({ userId: z.number().int().positive(), banned: z.boolean() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); if (input.userId === ctx.user.id) throw new Error("لا يمكن حظر الحساب الإداري الحالي"); const existing = (await db.select().from(blocks).where(and(eq(blocks.blockerId, ctx.user.id), eq(blocks.blockedId, input.userId))).limit(1))[0]; if (input.banned && !existing) await db.insert(blocks).values({ blockerId: ctx.user.id, blockedId: input.userId }); if (!input.banned && existing) await db.delete(blocks).where(eq(blocks.id, existing.id)); await db.insert(adminAuditLogs).values({ adminId: ctx.user.id, action: input.banned ? "ban_user" : "unban_user", entity: "user", entityId: String(input.userId) }); return { success: true }; }),
    verifyUser: adminProcedure.input(z.object({ userId: z.number().int().positive(), verified: z.boolean() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(users).set({ verified: input.verified ? 1 : 0, verifiedAt: input.verified ? new Date() : null }).where(eq(users.id, input.userId)); await db.insert(adminAuditLogs).values({ adminId: ctx.user.id, action: input.verified ? "verify" : "unverify", entity: "user", entityId: String(input.userId) }); return { success: true }; }),
    setPublicId: adminProcedure.input(z.object({ userId: z.number().int().positive(), publicId: z.string().regex(/^[0-9]{4,20}$/) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const target = (await db.select({ openId: users.openId }).from(users).where(eq(users.id, input.userId)).limit(1))[0]; if (!target) throw new Error("User not found"); if (!canAssignPublicId(input.publicId, target.openId === ENV.ownerOpenId)) throw new Error("هذا الـID محجوز للإدارة أو غير صالح"); await db.update(users).set({ publicId: input.publicId }).where(eq(users.id, input.userId)); await db.insert(adminAuditLogs).values({ adminId: ctx.user.id, action: "set_public_id", entity: "user", entityId: String(input.userId), details: input.publicId }); return { success: true }; }),
    setCountry: adminProcedure.input(z.object({ userId: z.number().int().positive(), country: z.string().min(2).max(120) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(users).set({ country: input.country, countryLocked: 1 }).where(eq(users.id, input.userId)); await db.insert(adminAuditLogs).values({ adminId: ctx.user.id, action: "set_country", entity: "user", entityId: String(input.userId) }); return { success: true }; }),
    adjustCredits: adminProcedure.input(z.object({ userId: z.number().int().positive(), amount: z.number().int().refine(value => value !== 0), reason: z.string().min(3).max(300) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.insert(creditLedger).values({ userId: input.userId, amount: input.amount, kind: "adjustment", createdById: ctx.user.id, referenceId: input.reason }); await db.insert(adminAuditLogs).values({ adminId: ctx.user.id, action: "adjust_credits", entity: "user", entityId: String(input.userId), details: `${input.amount}: ${input.reason}` }); return { success: true }; }),
    updateReport: adminProcedure.input(z.object({ reportId: z.number().int().positive(), status: z.enum(["open", "reviewed", "dismissed", "resolved"]) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(reports).set({ status: input.status, reviewerId: ctx.user.id, reviewedAt: new Date() }).where(eq(reports.id, input.reportId)); await db.insert(adminAuditLogs).values({ adminId: ctx.user.id, action: "update_report", entity: "report", entityId: String(input.reportId), details: input.status }); return { success: true }; }),
    notifyUser: adminProcedure.input(z.object({ userId: z.number().int().positive(), body: z.string().min(1).max(500) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.insert(notifications).values({ recipientId: input.userId, actorId: ctx.user.id, type: "message", body: input.body }); await db.insert(adminAuditLogs).values({ adminId: ctx.user.id, action: "notify", entity: "user", entityId: String(input.userId), details: input.body }); return { success: true }; }),
    toggleProvider: adminProcedure.input(z.object({ providerId: z.number().int().positive(), active: z.boolean() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(aiProviders).set({ isActive: input.active ? 1 : 0 }).where(eq(aiProviders.id, input.providerId)); await db.insert(adminAuditLogs).values({ adminId: ctx.user.id, action: "toggle_ai_provider", entity: "ai_provider", entityId: String(input.providerId) }); return { success: true }; }),
    toggleModel: adminProcedure.input(z.object({ modelId: z.number().int().positive(), active: z.boolean() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(aiModels).set({ isActive: input.active ? 1 : 0 }).where(eq(aiModels.id, input.modelId)); await db.insert(adminAuditLogs).values({ adminId: ctx.user.id, action: "toggle_ai_model", entity: "ai_model", entityId: String(input.modelId) }); return { success: true }; }),
    audit: adminProcedure.query(async () => { const db = await getDb(); if (!db) return []; return db.select().from(adminAuditLogs).orderBy(desc(adminAuditLogs.createdAt)).limit(300); }),
  }),
  admin: router({ users: adminProcedure.query(async () => { const db = await getDb(); if (!db) return []; return db.select({ id: users.id, name: users.name, email: users.email, role: users.role, createdAt: users.createdAt, isOnline: users.isOnline, lastSeenAt: users.lastSeenAt }).from(users).orderBy(desc(users.createdAt)).limit(100); }), posts: adminProcedure.query(async () => { const db = await getDb(); if (!db) return []; return db.select({ post: posts, author: users }).from(posts).innerJoin(users, eq(posts.authorId, users.id)).orderBy(desc(posts.createdAt)).limit(100); }), deletePost: adminProcedure.input(z.object({ postId: z.number().int().positive() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const postComments = await db.select({ id: comments.id }).from(comments).where(eq(comments.postId, input.postId)); const commentIds = postComments.map(comment => comment.id); if (commentIds.length) await db.delete(commentLikes).where(inArray(commentLikes.commentId, commentIds)); await db.delete(comments).where(eq(comments.postId, input.postId)); await db.delete(postLikes).where(eq(postLikes.postId, input.postId)); await db.delete(postShares).where(eq(postShares.postId, input.postId)); await db.delete(postMedia).where(eq(postMedia.postId, input.postId)); await db.delete(notifications).where(eq(notifications.postId, input.postId)); await db.delete(posts).where(eq(posts.id, input.postId)); return { success: true }; }), setUserRole: adminProcedure.input(z.object({ userId: z.number().int().positive(), role: z.enum(["user", "admin"]) })).mutation(async ({ ctx, input }) => { if (input.userId === ctx.user.id) throw new Error("لا يمكن تغيير دور حسابك من هنا"); const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(users).set({ role: input.role }).where(eq(users.id, input.userId)); return { success: true }; }) }),
  presence: router({ markOnline: protectedProcedure.mutation(async ({ ctx }) => { const db = await getDb(); if (!db) return { success: false }; await db.update(users).set({ isOnline: 1, lastSeenAt: new Date() }).where(eq(users.id, ctx.user.id)); return { success: true }; }), markOffline: protectedProcedure.mutation(async ({ ctx }) => { const db = await getDb(); if (!db) return { success: false }; await db.update(users).set({ isOnline: 0, lastSeenAt: new Date() }).where(eq(users.id, ctx.user.id)); return { success: true }; }) }),
  messages: router({
    inbox: protectedProcedure.query(async ({ ctx }) => { const db = await getDb(); if (!db) return []; const ownMemberships = await db.select({ conversationId: conversationMembers.conversationId }).from(conversationMembers).where(eq(conversationMembers.userId, ctx.user.id)); const memberConversationIds = ownMemberships.map(row => row.conversationId); if (!memberConversationIds.length) return []; const rows = await db.select({ conversation: conversations, member: conversationMembers, user: users }).from(conversationMembers).innerJoin(conversations, eq(conversationMembers.conversationId, conversations.id)).innerJoin(users, eq(conversationMembers.userId, users.id)).where(and(inArray(conversationMembers.conversationId, memberConversationIds), ne(conversationMembers.userId, ctx.user.id))); const inboxItems = rows.map(({ conversation, user }) => ({ conversationId: conversation.id, updatedAt: conversation.updatedAt, participant: { id: user.id, name: user.name, avatarUrl: user.avatarUrl, publicId: user.publicId, verified: user.verified, level: user.level } })); const visibleItems = (await Promise.all(inboxItems.map(async item => ({ item, blocked: await isBlocked(ctx.user.id, item.participant.id) })))).filter(entry => !entry.blocked).map(entry => entry.item); return sortInboxItems(visibleItems); }),
    getOrCreateConversation: protectedProcedure.input(z.object({ userId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { if (await isBlocked(ctx.user.id, input.userId)) throw new Error("Messaging unavailable"); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const acceptedFollow = await db.select({ id: follows.id }).from(follows).where(and(or(and(eq(follows.followerId, ctx.user.id), eq(follows.followingId, input.userId)), and(eq(follows.followerId, input.userId), eq(follows.followingId, ctx.user.id))), eq(follows.status, "accepted"))).limit(1); if (!acceptedFollow.length) throw new Error("لا يمكن إرسال رسالة قبل قبول المتابعة"); const existing = await getConversation(ctx.user.id, input.userId); if (existing) return { conversationId: existing }; const result = await db.insert(conversations).values({}); const conversationId = Number(result[0].insertId); await db.insert(conversationMembers).values([{ conversationId, userId: ctx.user.id }, { conversationId, userId: input.userId }]); return { conversationId }; }),
    participant: protectedProcedure.input(z.object({ conversationId: z.number().int().positive() })).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) return null; const member = (await db.select().from(conversationMembers).where(and(eq(conversationMembers.conversationId, input.conversationId), eq(conversationMembers.userId, ctx.user.id))).limit(1))[0]; if (!member) throw new Error("Not allowed"); const result = await db.select({ user: users }).from(conversationMembers).innerJoin(users, eq(conversationMembers.userId, users.id)).where(and(eq(conversationMembers.conversationId, input.conversationId), ne(conversationMembers.userId, ctx.user.id))).limit(1); return result[0]?.user || null; }),
    list: protectedProcedure.input(z.object({ conversationId: z.number().int().positive() })).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) return []; const member = (await db.select().from(conversationMembers).where(and(eq(conversationMembers.conversationId, input.conversationId), eq(conversationMembers.userId, ctx.user.id))).limit(1))[0]; if (!member) throw new Error("Not allowed"); await db.update(messages).set({ deliveredAt: new Date() }).where(and(eq(messages.conversationId, input.conversationId), ne(messages.senderId, ctx.user.id))); return db.select().from(messages).where(eq(messages.conversationId, input.conversationId)).orderBy(messages.createdAt); }),
    send: protectedProcedure.input(z.object({ conversationId: z.number().int().positive(), messageType: z.enum(["text", "image", "video", "audio"]).default("text"), body: z.string().max(5000).optional(), mediaUrl: storedImageUrl.optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const member = (await db.select().from(conversationMembers).where(and(eq(conversationMembers.conversationId, input.conversationId), eq(conversationMembers.userId, ctx.user.id))).limit(1))[0]; if (!member) throw new Error("Not allowed"); const otherMembers = await db.select().from(conversationMembers).where(and(eq(conversationMembers.conversationId, input.conversationId), ne(conversationMembers.userId, ctx.user.id))); const recipient = otherMembers[0]?.userId; if (!recipient || await isBlocked(ctx.user.id, recipient)) throw new Error("Messaging unavailable"); const acceptedFollow = await db.select({ id: follows.id }).from(follows).where(and(or(and(eq(follows.followerId, ctx.user.id), eq(follows.followingId, recipient)), and(eq(follows.followerId, recipient), eq(follows.followingId, ctx.user.id))), eq(follows.status, "accepted"))).limit(1); if (!acceptedFollow.length) throw new Error("لا يمكن إرسال رسالة قبل قبول المتابعة"); const result = await db.insert(messages).values({ ...input, senderId: ctx.user.id }); await Promise.all(otherMembers.map(member => createNotification(member.userId, ctx.user.id, "message"))); return { id: Number(result[0].insertId) }; }),
    read: protectedProcedure.input(z.object({ conversationId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(conversationMembers).set({ lastReadAt: new Date() }).where(and(eq(conversationMembers.conversationId, input.conversationId), eq(conversationMembers.userId, ctx.user.id))); await db.update(messages).set({ readAt: new Date() }).where(and(eq(messages.conversationId, input.conversationId), ne(messages.senderId, ctx.user.id))); return { success: true }; }),
    update: protectedProcedure.input(z.object({ messageId: z.number().int().positive(), body: z.string().min(1).max(5000) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const message = (await db.select().from(messages).where(and(eq(messages.id, input.messageId), eq(messages.senderId, ctx.user.id))).limit(1))[0]; if (!message || Date.now() - new Date(message.createdAt).getTime() > 60_000) throw new Error("لا يمكن تعديل الرسالة بعد مرور دقيقة"); await db.update(messages).set({ body: input.body }).where(eq(messages.id, input.messageId)); return { success: true }; }),
    unsend: protectedProcedure.input(z.object({ messageId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const message = (await db.select().from(messages).where(and(eq(messages.id, input.messageId), eq(messages.senderId, ctx.user.id))).limit(1))[0]; if (!message || Date.now() - new Date(message.createdAt).getTime() > 60_000) throw new Error("لا يمكن إلغاء الرسالة بعد مرور دقيقة"); await db.delete(messages).where(eq(messages.id, input.messageId)); return { success: true }; }),
  }),
  media: router({ upload: protectedProcedure.input(z.object({ fileName: z.string().max(180), mimeType: z.enum(["image/jpeg", "image/webp", "image/png", "image/gif", "image/svg+xml", "image/avif", "image/heic", "image/heif", "video/mp4", "audio/webm", "audio/mpeg"]), data: z.string().min(20).max(20_000_000) })).mutation(async ({ ctx, input }) => { const buffer = decodeUploadData(input.data); const result = await storagePut(`${ctx.user.id}/uploads/${Date.now()}-${input.fileName.replace(/[^a-zA-Z0-9._-]/g, "-")}`, buffer, input.mimeType); return result; }) }),
  splash: router({ upload: adminProcedure.input(z.object({ fileName: z.string().max(180), mimeType: z.string().regex(/^image\//), data: z.string().min(20).max(20_000_000) })).mutation(async ({ ctx, input }) => { const buffer = decodeUploadData(input.data); return storagePut(`${ctx.user.id}/splash/${Date.now()}-${input.fileName.replace(/[^a-zA-Z0-9._-]/g, "-")}`, buffer, input.mimeType); }), active: publicProcedure.query(async () => { const db = await getDb(); if (!db) return []; return db.select().from(splashSlides).where(eq(splashSlides.isActive, 1)).orderBy(splashSlides.sortOrder); }), adminList: adminProcedure.query(async () => { const db = await getDb(); if (!db) return []; return db.select().from(splashSlides).orderBy(splashSlides.sortOrder); }), create: adminProcedure.input(z.object({ title: z.string().min(2).max(180), subtitle: z.string().max(1000).optional(), imageUrl: z.string(), fileKey: z.string() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const active = await db.select().from(splashSlides).where(eq(splashSlides.isActive, 1)); if (active.length >= 3) throw new Error("يمكن تفعيل ثلاث شرائح فقط"); const result = await db.insert(splashSlides).values(input); return { id: Number(result[0].insertId) }; }), update: adminProcedure.input(z.object({ id: z.number().int().positive(), isActive: z.number().int().min(0).max(1).optional(), title: z.string().max(180).optional(), subtitle: z.string().max(1000).optional() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); if (input.isActive === 1) { const active = await db.select().from(splashSlides).where(and(eq(splashSlides.isActive, 1), ne(splashSlides.id, input.id))); if (active.length >= 3) throw new Error("يمكن تفعيل ثلاث شرائح فقط"); } await db.update(splashSlides).set(input).where(eq(splashSlides.id, input.id)); return { success: true }; }) }),
});

export type AppRouter = typeof appRouter;
