import { useState } from "react";
import { FileCheck, Loader2, Upload } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
function readFile(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); }); }
export default function AccountVerificationCard({ profile }: { profile: any }) {
  const [accountType, setAccountType] = useState<"client" | "designer">(profile.accountType || "client"); const [birthYear, setBirthYear] = useState(String(profile.birthYear || "")); const [front, setFront] = useState<File | null>(null); const [back, setBack] = useState<File | null>(null); const [cv, setCv] = useState<File | null>(null); const updateType = trpc.account.updateType.useMutation({ onSuccess: () => toast.success("تم حفظ نوع الحساب والعمر"), onError: error => toast.error(error.message) }); const upload = trpc.media.upload.useMutation(); const submit = trpc.verification.submit.useMutation({ onSuccess: () => { toast.success("تم إرسال طلب التوثيق للمراجعة"); setFront(null); setBack(null); setCv(null); }, onError: error => toast.error(error.message) }); const status = profile.verificationStatus || "none"; const canSubmit = status === "none" || status === "rejected";
  const saveType = () => { const year = Number(birthYear); if (!Number.isInteger(year)) return toast.error("أدخل سنة الميلاد"); updateType.mutate({ accountType, birthYear: year }); }; const sendVerification = async () => { if (!front || !back || !cv) return toast.error("أرفق البطاقة من الأمام والخلف وملف CV"); try { const stored = await Promise.all([front, back, cv].map(async file => upload.mutateAsync({ fileName: file.name, mimeType: file.type as any, data: await readFile(file) }))); submit.mutate({ idFrontUrl: stored[0].url, idBackUrl: stored[1].url, cvUrl: stored[2].url }); } catch (error) { toast.error(error instanceof Error ? error.message : "تعذر رفع المستندات"); } };
  return <section className="mt-5 rounded-[1.5rem] border border-neutral-200 bg-white p-5"><div className="flex items-center gap-2"><FileCheck className="text-[#c38a10]" /><div><h2 className="font-display font-bold">نوع الحساب والتحقق</h2><p className="text-xs text-neutral-500">بيانات التحقق خاصة بالإدارة وتختفي من واجهتك بعد الإرسال.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><select value={accountType} onChange={event => setAccountType(event.target.value as "client" | "designer")} className="rounded-xl border border-neutral-200 px-3 py-2 text-sm"><option value="client">حساب عميل</option><option value="designer">حساب مصمم</option></select><input value={birthYear} onChange={event => setBirthYear(event.target.value)} type="number" min="1900" max={new Date().getFullYear() - 13} placeholder="سنة الميلاد" className="rounded-xl border border-neutral-200 px-3 py-2 text-sm" /><Button onClick={saveType} disabled={updateType.isPending} className="rounded-xl bg-neutral-950 text-white">حفظ البيانات</Button></div>{canSubmit ? <><div className="mt-5 grid gap-3 md:grid-cols-3">{[["صورة البطاقة — الوجه", front, setFront, "image/jpeg,image/png,image/webp"], ["صورة البطاقة — الظهر", back, setBack, "image/jpeg,image/png,image/webp"], ["السيرة الذاتية CV", cv, setCv, ".pdf,.doc,.docx,application/pdf"]].map(([label, file, setter, accept]) => <label key={label as string} className="flex cursor-pointer items-center gap-2 rounded-xl border border-dashed border-neutral-300 p-3 text-xs text-neutral-500"><Upload className="h-4 w-4" /><span className="min-w-0 flex-1 truncate">{file ? (file as File).name : label as string}<input type="file" accept={accept as string} className="hidden" onChange={event => (setter as (file: File | null) => void)(event.target.files?.[0] || null)} /></span></label>)}</div><div className="mt-4 flex items-center justify-between gap-3"><p className="text-xs text-neutral-500">الحالة الحالية: <strong>{status === "rejected" ? "مرفوض — يمكنك إعادة التقديم" : status}</strong></p><Button onClick={sendVerification} disabled={submit.isPending || upload.isPending} className="rounded-xl bg-[#f6c94c] font-bold text-neutral-950">{submit.isPending || upload.isPending ? <Loader2 className="animate-spin" /> : "إرسال للتوثيق"}</Button></div></> : <div className="mt-5 rounded-xl bg-[#f8f7f3] p-4 text-sm text-neutral-600">تم استلام البيانات لدى الإدارة. لا تظهر المستندات داخل الملف. {status === "approved" ? "تم اعتماد التحقق." : "طلبك قيد المراجعة."}</div>}</section>;
}
