import { useEffect, useState } from "react";
import { Link, useLocation } from "wouter";
import { trpc } from "@/lib/trpc";
import { Bell, Compass, LogOut, MessageCircle, Plus, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";

const logo = "/manus-storage/king-designer-mark_ec43f952.png";
export default function AppChrome({ children, title }: { children: React.ReactNode; title?: string }) {
  const { user, isAuthenticated, logout } = useAuth(); const [, navigate] = useLocation(); const [query, setQuery] = useState(""); const markOnline = trpc.presence.markOnline.useMutation(); const markOffline = trpc.presence.markOffline.useMutation(); useEffect(() => { if (!isAuthenticated) return; markOnline.mutate(); const handleOffline = () => markOffline.mutate(); window.addEventListener("beforeunload", handleOffline); return () => { window.removeEventListener("beforeunload", handleOffline); }; }, [isAuthenticated]);
  return <div dir="rtl" className="min-h-screen bg-[#f8f7f3] text-neutral-950"><header className="sticky top-0 z-30 border-b border-neutral-200/80 bg-[#f8f7f3]/90 backdrop-blur-xl"><div className="container flex h-20 items-center justify-between gap-5"><Link href="/" className="flex items-center gap-3"><img src={logo} alt="KING DESIGNER" className="h-11 w-11 object-contain" /><div className="hidden sm:block"><div className="font-display text-sm font-extrabold">KING DESIGNER</div><div className="text-[10px] font-semibold text-neutral-500">مساحة تصنع الفرق</div></div></Link><form onSubmit={e => { e.preventDefault(); if (query.trim()) navigate(`/search?q=${encodeURIComponent(query.trim())}`); }} className="hidden flex-1 items-center justify-center md:flex"><div className="flex w-full max-w-md items-center gap-3 rounded-2xl border border-neutral-200 bg-white px-4 py-2.5 text-sm text-neutral-400"><Search className="h-4 w-4" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="ابحث عن مصمم أو مشروع أو وسم" className="w-full bg-transparent outline-none placeholder:text-neutral-400" /></div></form><nav className="flex items-center gap-1"><Link href="/" className="grid h-10 w-10 place-items-center rounded-xl text-neutral-500 hover:bg-white" aria-label="التغذية"><Compass className="h-4 w-4" /></Link><Link href="/messages" className="grid h-10 w-10 place-items-center rounded-xl text-neutral-500 hover:bg-white" aria-label="الرسائل"><MessageCircle className="h-4 w-4" /></Link><Link href="/notifications" className="grid h-10 w-10 place-items-center rounded-xl text-neutral-500 hover:bg-white" aria-label="الإشعارات"><Bell className="h-4 w-4" /></Link>{user?.role === "admin" && <Link href="/admin" className="hidden rounded-xl bg-[#fff4cf] px-3 py-2 text-xs font-bold text-[#a36e00] sm:block">الإدارة</Link>}{isAuthenticated ? <><Link href={`/profile/${user?.id}`} className="mr-1 rounded-xl border border-neutral-200 bg-white px-3 py-2 text-xs font-bold">ملفي</Link><button onClick={() => logout()} className="grid h-10 w-10 place-items-center rounded-xl text-neutral-500 hover:bg-white" aria-label="تسجيل الخروج"><LogOut className="h-4 w-4" /></button></> : <Button onClick={() => startLogin()} className="rounded-xl bg-neutral-950 text-white">دخول</Button>}</nav></div></header><main>{title && <div className="container pt-8"><h1 className="font-display text-2xl font-extrabold">{title}</h1></div>}{children}</main></div>;
}
