import { useState } from "react";
import { BriefcaseBusiness, CheckCircle2, Crown, Loader2, Palette, UserRound } from "lucide-react";
import { useLocation } from "wouter";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";

export default function PostLoginOnboarding({ user }: { user: any }) {
  const [, navigate] = useLocation();
  const [accountType, setAccountType] = useState<"client" | "designer">(user.accountType === "designer" ? "designer" : "client");
  const [saving, setSaving] = useState(false);
  const update = trpc.account.updateType.useMutation();
  const finish = async () => { setSaving(true); try { await update.mutateAsync({ accountType, birthYear: user.birthYear || new Date().getFullYear() - 25 }); localStorage.setItem(`kd-onboarding-${user.id}`, "done"); navigate(`/profile/${user.id}${accountType === "designer" ? "?edit=1" : ""}`); } catch (error) { toast.error(error instanceof Error ? error.message : "تعذر حفظ نوع الحساب"); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-50 grid place-items-center bg-[#f8f7f3] p-4" dir="rtl"><div className="w-full max-w-3xl rounded-[2rem] border border-neutral-200 bg-white p-6 shadow-2xl sm:p-10"><div className="mx-auto max-w-xl text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-neutral-950 text-[#f6c94c] shadow-xl"><Crown /></div><p className="mt-5 text-xs font-bold tracking-[.18em] text-[#a36e00]">KING DESIGNER</p><h1 className="mt-2 font-display text-3xl font-extrabold">خلّينا نجهّز مساحتك</h1><p className="mt-3 text-sm leading-7 text-neutral-500">اختَر نوع الحساب لنضبط لك الصفحة والصلاحيات والمحتوى المناسب من أول دخول.</p></div>{user.role === "admin" ? <div className="mx-auto mt-8 max-w-md rounded-2xl border border-[#ead48d] bg-[#fff8df] p-6 text-center"><CheckCircle2 className="mx-auto h-10 w-10 text-[#a36e00]" /><h2 className="mt-3 font-display text-xl font-bold">حساب إداري موثّق</h2><p className="mt-2 text-sm text-neutral-600">ستظهر لك لوحة الإدارة وشارة الإدارة والهوية الذهبية الخاصة بالحساب الإداري.</p><Button onClick={finish} disabled={saving} className="mt-5 rounded-xl bg-neutral-950 text-white">دخول إلى الملف الإداري</Button></div> : <><div className="mt-8 grid gap-4 md:grid-cols-2"><button onClick={() => setAccountType("designer")} className={`rounded-2xl border p-6 text-right transition ${accountType === "designer" ? "border-[#c38a10] bg-[#fff8df] ring-2 ring-[#f6c94c]/30" : "border-neutral-200 hover:border-[#d9ba68]"}`}><Palette className="h-8 w-8 text-[#a36e00]" /><h2 className="mt-4 font-display text-xl font-bold">مصمم</h2><p className="mt-2 text-sm leading-7 text-neutral-500">انتقل مباشرة إلى تعديل البورتفوليو وأضف الخبرة والمهارات والأدوات والأعمال.</p></button><button onClick={() => setAccountType("client")} className={`rounded-2xl border p-6 text-right transition ${accountType === "client" ? "border-[#c38a10] bg-[#fff8df] ring-2 ring-[#f6c94c]/30" : "border-neutral-200 hover:border-[#d9ba68]"}`}><UserRound className="h-8 w-8 text-[#a36e00]" /><h2 className="mt-4 font-display text-xl font-bold">عميل</h2><p className="mt-2 text-sm leading-7 text-neutral-500">ملف بسيط باسمك وصورتك ونبذة قصيرة لاكتشاف المصممين والتواصل معهم.</p></button></div><div className="mt-7 flex justify-center"><Button onClick={finish} disabled={saving} className="h-12 min-w-56 rounded-xl bg-neutral-950 text-white">{saving ? <Loader2 className="animate-spin" /> : <><BriefcaseBusiness className="ml-2 h-4 w-4" />متابعة</>}</Button></div></>}</div></div>;
}
