import { useEffect, useState } from "react";
import { FileUp, Loader2, X } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";

function readFile(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); }); }
export default function ReportDialog({ open, targetType, targetId, onClose, onSuccess }: { open: boolean; targetType: "user" | "post" | "comment" | "message" | "story"; targetId: number; onClose: () => void; onSuccess: () => void }) {
  const [reason, setReason] = useState(""); const [file, setFile] = useState<File | null>(null); const [duration, setDuration] = useState<number | undefined>(); const upload = trpc.media.upload.useMutation(); const create = trpc.reports.create.useMutation({ onSuccess: () => { toast.success("تم إرسال البلاغ للمراجعة"); onSuccess(); onClose(); setReason(""); setFile(null); }, onError: error => toast.error(error.message) });
  useEffect(() => { if (!file || !file.type.startsWith("video/")) return; const video = document.createElement("video"); video.preload = "metadata"; video.onloadedmetadata = () => { setDuration(Number.isFinite(video.duration) ? Math.ceil(video.duration) : undefined); URL.revokeObjectURL(video.src); }; video.src = URL.createObjectURL(file); return () => URL.revokeObjectURL(video.src); }, [file]);
  if (!open) return null;
  const submit = async () => { if (reason.trim().length < 3) return toast.error("اكتب سبب البلاغ بوضوح"); if (duration !== undefined && duration > 60) return toast.error("الفيديو المرفق يجب ألا يتجاوز دقيقة واحدة"); try { let attachmentUrl: string | undefined; let attachmentType: string | undefined; if (file) { const stored = await upload.mutateAsync({ fileName: file.name, mimeType: file.type as any, data: await readFile(file) }); attachmentUrl = stored.url; attachmentType = file.type; } create.mutate({ targetType, targetId, reason: reason.trim(), attachmentUrl, attachmentType, attachmentDuration: duration }); } catch (error) { toast.error(error instanceof Error ? error.message : "تعذر رفع المرفق"); } };
  return <div className="fixed inset-0 z-50 grid place-items-center bg-neutral-950/50 p-4 backdrop-blur-sm"><div className="w-full max-w-lg rounded-[1.5rem] bg-white p-6 shadow-2xl" dir="rtl"><div className="flex items-center justify-between"><div><h2 className="font-display text-lg font-bold">إبلاغ عن محتوى</h2><p className="mt-1 text-xs text-neutral-500">اكتب التفاصيل وأرفق صورة أو فيديو قصير عند الحاجة.</p></div><button onClick={onClose} aria-label="إغلاق"><X className="h-5 w-5 text-neutral-400" /></button></div><Textarea value={reason} onChange={event => setReason(event.target.value)} placeholder="سبب البلاغ" className="mt-4 min-h-28 rounded-xl" />{file && <div className="mt-3 overflow-hidden rounded-xl border border-neutral-200 p-2 text-xs"><p className="font-bold">معاينة: {file.name}</p>{file.type.startsWith("image/") && <img src={URL.createObjectURL(file)} alt="معاينة المرفق" className="mt-2 max-h-40 w-full rounded-lg object-contain" />}{duration !== undefined && <p className="mt-1 text-neutral-500">المدة: {duration} ثانية</p>}</div>}<label className="mt-3 flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed border-neutral-300 p-4 text-xs text-neutral-500"><FileUp className="h-4 w-4" />إرفاق صورة أو فيديو حتى دقيقة<input type="file" accept="image/*,video/mp4,video/webm" className="hidden" onChange={event => setFile(event.target.files?.[0] || null)} /></label><Button onClick={submit} disabled={upload.isPending || create.isPending} className="mt-4 h-11 w-full rounded-xl bg-neutral-950 text-white">{upload.isPending || create.isPending ? <Loader2 className="animate-spin" /> : "إرسال البلاغ"}</Button></div></div>;
}
